# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
    inputs:
      weeklyReleaseNumber:
        description: 'Weekly Release Number'     
        required: true

jobs:  
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Branch name
        run: |
          YEAR_AND_WEEK="$(date +"rel/%y.%U.")"
          export BRANCH_NAME BRANCH_NAME="${YEAR_AND_WEEK}${{ github.event.inputs.weeklyReleaseNumber }}"
          echo BRANCH_NAME

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
