name: Dev to Staging Release

on:
  workflow_dispatch:
    inputs:
      weeklyReleaseNumber:
        description: 'Number of the release of the week'
        required: true
      versionBump:
        description: |
          How would you like to bump the version?
          major (2.0.0) |
          minor (1.2.0) |
          patch (1.1.1) |
          pre-release major (2.0.0-beta.1) |
          pre-release minor (1.2.0-beta.1) |
          pre-release patch (1.1.1-beta.1) |
          pre-release (1.1.1-beta.1)
        required: true  

env: 
  testing_env: "placeHolder"

jobs:  
  Create_Staging_PR:
    runs-on: ubuntu-latest

    # outputs:
    #   test-result: ${{ steps.set_outputs.outputs.test-result }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Prepare BRANCH_NAME and PR_TITLE
        id: vars
        run: |
          echo $testing_env
          YEAR_AND_WEEK="$(date +"%y.%U.")"
          VERSION=${YEAR_AND_WEEK}${{ github.event.inputs.weeklyReleaseNumber }}
          export BRANCH_NAME BRANCH_NAME="rel/${VERSION}"
          export PR_TITLE PR_TITLE="chore: release ${VERSION}"
          echo ::set-output name=branch_name::${BRANCH_NAME}
          echo ::set-output name=pr_title::${PR_TITLE}
          ${{ env.testing_env = "changed" }}

      # - name: set outputs
      #   id: set_outputs
      #   run: |
      #     echo "::set-output name=test-result::$TEST_RESULT"

      - name: Reset promotion branch
        run: |
          echo $testing_env
          git fetch origin dev:dev
          git reset --hard dev

      - name: Make changes to pull request
        run: |
          npm i -g @jsdevtools/version-bump-prompt
          bump ${{ github.event.inputs.versionBump }}
          npm i -g conventional-changelog-cli
          conventional-changelog -p angular -i CHANGELOG.md -s
          
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          title: ${{ steps.vars.outputs.pr_title }}
          body: ${{ steps.vars.outputs.pr_title }}
          commit-message: ${{ steps.vars.outputs.pr_title }}
          branch: ${{ steps.vars.outputs.branch_name }}
          delete-branch: true
          base: main
          assignees: ${{ github.actor }}
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              "url": "${{ steps.cpr.outputs.pull-request-url }}",
              "operation": "${{ steps.cpr.outputs.pull-request-operation }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      # - id: automerge
      #   name: automerge
      #   uses: "pascalgn/automerge-action@v0.15.3"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     PULL_REQUEST: ${{ steps.cpr.outputs.pull-request-number }}

      # - name: feedback
      #   if: ${{ steps.automerge.outputs.mergeResult }} == "merged"
      #   run: |
      #     echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} merged!"
          
      - name: Enable Pull Request Automerge
        id: mergeeeee
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}

      # - name: call-workflow-passing-data
      #   uses: TorahitoYamashita/cicd_test/.github/workflows/reusable-workflow.yml@main
      #   with:
      #     branch_name: ${{ steps.vars.outputs.branch_name }}
      #     version_bump: ${{ github.event.inputs.versionBump }}
      
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Dump steps context
        id: stepssss
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"          

      - name: Testingggg
        run: |
          echo ${{ toJson(steps.stepssss.outputs) }}
          echo "$STEPS_CONTEXT"

  call-workflow-passing-data:
    needs: [Create_Staging_PR]
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      branch_name: ${{ needs.Create_Staging_PR.outputs.branch_name }}
      version_bump: ${{ github.event.inputs.versionBump }}

