# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
    inputs:
      weeklyReleaseNumber:
        description: 'Number of release this week'
        required: true
      versionBump:
        description: |-
          How would you like to bump the version?
          major (2.0.0)
          minor (1.2.0)
          patch (1.1.1)
          pre-release major (2.0.0-beta.1)
          pre-release minor (1.2.0-beta.1)
          pre-release patch (1.1.1-beta.1)
          pre-release (1.1.1-beta.1)
        required: true  

jobs:  
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Prepare BRANCH_NAME and PR_TITLE
        id: vars
        run: |
          YEAR_AND_WEEK="$(date +"%y.%U.")"
          VERSION=${YEAR_AND_WEEK}${{ github.event.inputs.weeklyReleaseNumber }}
          export BRANCH_NAME BRANCH_NAME="rel/${VERSION}"          
          export PR_TITLE PR_TITLE="chore: release ${VERSION}"          
          echo ::set-output name=branch_name::${BRANCH_NAME}
          echo ::set-output name=pr_title::${PR_TITLE}

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Make changes to pull request
        run: date +%s > report.txt

      - name: Reset promotion branch
        run: |
          git fetch origin dev:dev
          git reset --hard dev

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:          
          title: ${{ steps.vars.outputs.pr_title }}          
          body: ${{ steps.vars.outputs.pr_title }}
          commit-message: ${{ steps.vars.outputs.pr_title }}
          branch: ${{ steps.vars.outputs.branch_name }}
          delete-branch: true
          base: main
          assignees: ${{ github.actor }}
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>