# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
    inputs:
      weeklyReleaseNumber:
        description: 'Weekly Release Number'     
        required: true

jobs:  
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Prepare BRANCH_NAME and PR_TITLE
        id: vars
        run: |
          YEAR_AND_WEEK="$(date +"%y.%U.")"
          VERSION=${YEAR_AND_WEEK}${{ github.event.inputs.weeklyReleaseNumber }}
          export BRANCH_NAME BRANCH_NAME="rel/${VERSION}"          
          export PR_TITLE PR_TITLE="chore: release ${VERSION}"          
          echo ::set-output name=branch_name::${BRANCH_NAME}
          echo ::set-output name=pr_title::${PR_TITLE}

      - name: Prepare BRANCH_NAME and PR_TITLE
        id: vars
        run: |
          YEAR_AND_WEEK="$(date +"%y.%U.")"
          VERSION=${YEAR_AND_WEEK}${{ github.event.inputs.weeklyReleaseNumber }}
          export BRANCH_NAME BRANCH_NAME="rel/${VERSION}"          
          export PR_TITLE PR_TITLE="chore: release ${VERSION}"          
          echo ::set-output name=branch_name::${BRANCH_NAME}
          echo ::set-output name=pr_title::${PR_TITLE}

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Make changes to pull request
        run: date +%s > report.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: update authors
          title: ${{ steps.vars.outputs.pr_title }}
          body: Credit new contributors by updating AUTHORS
          branch: ${{ steps.vars.outputs.branch_name }}
          delete-branch: true
          # commit-message: ${PR_TITLE}
          # title: ${PR_TITLE}
          # body: ${PR_TITLE}
          # branch: ${BRANCH_NAME}
          # delete-branch: true
          # base: dev
          # assignees: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          # author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>