name: Staging to Production Release

on:
  workflow_dispatch:
    inputs:
      weeklyReleaseNumber:
        description: 'Number of the release of the week'
        required: true

jobs:  
  Create_Production_PR:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Prepare BRANCH_NAME and PR_TITLE
        id: vars
        run: |
          YEAR_AND_WEEK="$(date +"%y.%U.")"
          VERSION=${YEAR_AND_WEEK}${{ github.event.inputs.weeklyReleaseNumber }}
          export PR_TITLE PR_TITLE="chore: release ${VERSION}"
          echo ::set-output name=pr_title::${PR_TITLE}

      - name: Reset promotion branch
        run: |
          git fetch origin dev:dev
          git reset --hard dev
          
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          title: ${{ steps.vars.outputs.pr_title }}
          body: ${{ steps.vars.outputs.pr_title }}
          commit-message: ${{ steps.vars.outputs.pr_title }}
          # branch: ${{ steps.vars.outputs.branch_name }}
          delete-branch: true
          base: main
          assignees: ${{ github.actor }}
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              "url": "${{ steps.cpr.outputs.pull-request-url }}",
              "what_pr": "Dev to Staging release",
              "operation": "${{ steps.cpr.outputs.pull-request-operation }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      # - id: automerge
      #   name: automerge
      #   uses: "pascalgn/automerge-action@v0.15.3"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     PULL_REQUEST: ${{ steps.cpr.outputs.pull-request-number }}

      # - name: feedback
      #   if: ${{ steps.automerge.outputs.mergeResult }} == "merged"
      #   run: |
      #     echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} merged!"
          
      - name: Enable Pull Request Automerge
        id: mergeeeee
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}

      # - name: call-workflow-passing-data
      #   uses: TorahitoYamashita/cicd_test/.github/workflows/reusable-workflow.yml@main
      #   with:
      #     branch_name: ${{ steps.vars.outputs.branch_name }}
      #     version_bump: ${{ github.event.inputs.versionBump }}
      
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Dump steps context
        id: stepssss
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"          
