name: Release Tag

# on:
#   push:
#     tags:
#       - "v[0-9]+.[0-9]+.[0-9]+"
on:
  workflow_call:
    # inputs:
    #   tag:
    #     required: true
    #     type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Refresh tags"
        id: tag
        run: git fetch --tags --force # Is currently required for v3 due to https://github.com/actions/checkout/issues/290
      - uses: ericcornelissen/git-tag-annotation-action@v2
        id: tag-data

      - name: Logginggg
        run: |
          echo ${{ steps.tag-data.outputs.git-tag-annotation }}

      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@v2
        with:
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
          release_title: ${{ steps.tag-data.outputs.git-tag-annotation }}
          release_text: ${{ steps.tag-data.outputs.git-tag-annotation }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

