name: Sync Staging to Dev

on: status

jobs:
  if_error_or_failure:
    runs-on: ubuntu-latest
    if: >-
      github.event.state == 'success' &&
      contains(github.event.target_url, 'staging')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: staging

      - name: staging to dev
        id: cpr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "staging"
          destination_branch: "dev"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "automerge"

      - name: staging to main
        id: cpr2
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "staging"
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST: ${{ steps.cpr.outputs.pr_number }}
      # - name: Pull Request Automerge
      #   if: steps.cpr.outputs.has_changed_files
      #   uses: peter-evans/enable-pull-request-automerge@v2
      #   with:
      #     token: ${{ secrets.PAT }}
      #     pull-request-number: ${{ steps.cpr.outputs.pr_number }}

      # - env:
      #     DESCRIPTION: ${{ github.event.description }}
      #     STATE: ${{ github.event.state }}
      #     CONTEXT: ${{ github.event.context }}
      #     EVENT_SHA: ${{ github.event.sha }}
      #     STAGING_SHA: ${{ toJson(github.event.branches) }}
      #     STATUSES: ${{ github.event.target_url }}
      #   run: |
      #     echo DESCRIPTION: $DESCRIPTION
      #     echo STATE: $STATE
      #     echo CONTEXT: $CONTEXT
      #     echo EVENT_SHA: $EVENT_SHA
      #     echo EVENT_SHA: $STAGING_SHA
      #     echo GIT_BRANCH: ${GITHUB_REF#refs/heads/}
      #     echo STATUSES: $STATUSES

      # - name: Conditionally Run
      #   if: contains(env.STATUSES, 'staging')
      #   run: |
      #     echo "this works"
      # - name: Conditionally Run
      #   if: contains(github.event.target_url, 'staging')
      #   run: |
      #     echo "this works too"

      - name: Dump GitHub event context
        env:
          GITHUB_EVENT_CONTEXT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_EVENT_CONTEXT"
      - name: Dump GitHub event context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Dump steps context
        id: stepssss
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"          
