name: Sync Staging to Dev

on: 
  status:
    branches: [staging]

jobs:
  if_error_or_failure:
    runs-on: ubuntu-latest
    if: github.event.state == 'success'
    # if: >-
    #   github.event.state == 'error' ||
    #   github.event.state == 'failure'
    steps:
      - env:
          DESCRIPTION: ${{ github.event.description }}
          STATE: ${{ github.event.state }}
          CONTEXT: ${{ github.event.context }}
          EVENT_SHA: ${{ github.event.sha }}
          STAGING_SHA: ${{ toJson(github.event.branches) }}
        run: |
          echo DESCRIPTION: $DESCRIPTION
          echo STATE: $STATE
          echo CONTEXT: $CONTEXT
          echo EVENT_SHA: $EVENT_SHA
          echo EVENT_SHA: $STAGING_SHA
          for i in "${${{ github.event.branches }}[@]}"
          do
            : 
            echo "$i"
          done

      - name: Dump GitHub event context
        env:
          GITHUB_EVENT_CONTEXT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_EVENT_CONTEXT"
      - name: Dump GitHub event context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Dump steps context
        id: stepssss
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"          
